import type { UiLanguage } from "./marketTypes";

export function getMarketCopy(language: UiLanguage) {
  if (language === "en-US") {
    return {
      allCategory: "All",
      allSources: "All Sources",
      importSteps: [
        { key: "prepare" as const, label: "Request Received", detail: "Validate source and import parameters" },
        { key: "dispatch" as const, label: "Pipeline Connected", detail: "Submit the unified import transaction" },
        { key: "processing" as const, label: "Processing", detail: "Wait for archiving, snapshotting, and source registration" },
        { key: "done" as const, label: "Completed", detail: "Ready to continue governance in the workspace" },
      ],
      externalEyebrow: "External Market & Import",
      externalTitle: "Discover Mature Skills First",
      externalSubtitle:
        "Browse real skills from the external market, filter them by board and category, and pull them into the unified governance pipeline with one click.",
      externalSearchAria: "Search external skills",
      externalSearchPlaceholder: "Search skills or repositories",
      externalAllTime: "All Time",
      externalTrending: "Trending",
      externalHot: "Hot",
      externalResultsLabel: "External Market",
      externalResultsTitle: "External Skills",
      externalResultsHint: "skills.sh",
      externalResultsCount: (count: number) => `${count} skills`,
      externalSourcePrefix: (value: string) => `Repository ${value}`,
      externalInstalls: (value: string) => `${value} installs`,
      externalImportAction: "Import",
      externalImportSuccess: (name: string) => `${name} was imported from the external market.`,
      externalImportErrorTitle: (name: string) => `${name} import failed`,
      externalImportErrorPrefix: "External market import failed",
      externalInstalled: "In Library",
      externalDetailAction: "View Details",
      externalConflictAction: "View Existing Skill",
      externalInstalledHint: (name: string) => `Already available in the skill library as ${name}.`,
      externalConflictHint: (name: string, slug: string) => `Slug ${slug} is already owned by ${name}.`,
      externalDetailSummaryLabel: "Overview",
      externalDetailRepoLabel: "Repository",
      externalDetailSkillIdLabel: "Skill ID",
      externalDetailSourcePathLabel: "Repository Path",
      externalDetailDocumentPathLabel: "Document Path",
      externalDetailPreviewLabel: "Documentation Preview",
      externalDetailPreviewEmpty: "No README or skill entry preview is available yet.",
      externalDetailLoadFailed: "Failed to load skill details",
      externalLoadFailed: "Failed to load external market",
      externalNoResults: "No external skills match the current filters",
      heroEyebrow: "",
      heroTitle: "Market & Import Console",
      heroSubtitle:
        "Every source enters the same import pipeline first: materialize directories, archive formally, create the initial snapshot, and register its source. The market page is both a template catalog and the unified entry for source filtering, import feedback, and source governance.",
      metricFeatured: "Featured Templates",
      metricCategories: "Categories",
      metricTotal: "Market Items",
      metricSourceTypes: "Covered Sources",
      quickImportLabel: "Quick Import",
      quickImportTitle: "Bring assets into formal governance",
      localSourceTitle: "Local Folder",
      localSourceDescription: "Connect an existing skill folder directly",
      pickFolder: "Choose Folder",
      repoImportLabel: "Repository Snapshot Import",
      repoImportHint: "Best for public skill repositories or team template repositories",
      gitUrlAria: "Git repository URL",
      gitUrlPlaceholder: "Enter a Git repository URL",
      gitSubdirAria: "Skill subdirectory in repository",
      gitSubdirPlaceholder: "Optional: skill subdirectory in the repository",
      importFromRepo: "Import from Repository",
      importStatusLabel: "Import Progress",
      importStatusWaiting: "Waiting for a new import task",
      importStateRunning: "Running",
      importStateFailed: "Failed",
      importStateSuccess: "Done",
      importStateIdle: "Idle",
      importSourceLabel: "Source",
      importStageLabel: "Stage",
      importTargetLabel: "Target",
      importStatusHint:
        "Current pipeline state is shown here after an intake starts.",
      importTarget: (name: string) => `Current target: ${name}`,
      pipelineLabel: "Unified Import Pipeline",
      pipelineTitle: "What happens automatically after import",
      pipelineStep1: "Materialize the source directory and validate it as an importable asset",
      pipelineStep2: "Create a formal skill record and copy it into the central workspace",
      pipelineStep3: "Create the initial snapshot automatically and mark it as the active version",
      pipelineStep4: "Write into `skill_sources` to keep source traceability",
      searchCatalogAria: "Search market templates",
      searchCatalogPlaceholder: "Search templates, categories, tags, or authors",
      governanceLabel: "Source Governance",
      governanceTitle: "Recently Imported Assets",
      governanceRecent: "Latest 10",
      governanceHint: "Filter recently imported skills by primary source and inspect their source details directly.",
      sourceFilterLabel: "Source Filter",
      sourceFilterTitle: "Review recent assets by primary source",
      sourceFilterDescription:
        "The latest updated skills are shown first. Their formal primary source records are loaded so you can verify that each import entered the correct governance pipeline.",
      noGovernedAssets: "There are no imported assets to govern yet",
      noGovernedAssetsForFilter: "No skills match the current source filter",
      updatedAt: (value: string) => `Updated ${value}`,
      sourceDetailFallback: "The source is registered, but there are no more details to display right now.",
      primarySource: (label: string) => `Primary source: ${label}`,
      openWorkspace: "Open Asset",
      historyLabel: "Import History",
      historyTitle: "Recent Import Records",
      historyCount: (count: number) => `${count} total`,
      historyHint: "Successful and failed records are kept so you can review issues, retry imports, and continue in the workspace.",
      historySummaryLabel: "History Overview",
      historySummaryTitle: "Unified import traceability",
      historySummaryDescription:
        "Every import records its source, result, target skill, and failure reason. Failed records can be retried directly, and successful records can jump back into the workspace.",
      success: "Success",
      failed: "Failed",
      historyLoadFailed: "Failed to load import history",
      reload: "Reload",
      noHistory: "There is no import history yet",
      recordedAt: (value: string) => `Recorded ${value}`,
      sourceType: (label: string) => `Source type: ${label}`,
      retryImport: "Retry Import",
      marketLoadFailed: "Failed to load market catalog",
      featuredLabel: "Featured Templates",
      featuredTitle: "Recommended First",
      featuredHint: "Prioritize the three main pipelines: platform governance, version governance, and team collaboration.",
      importToWorkspace: "Import to Library",
      catalogLabel: "Market Catalog",
      catalogTitle: "All Market Items",
      catalogBadge: "Unified Market Catalog",
      catalogCount: (count: number) => `${count} results`,
      noCatalogItems: "No market items match the current filters",
      importAction: "Import",
      localImportSuccess: "The local folder was imported and an initial snapshot was created.",
      localImportErrorTitle: "Local folder import failed",
      localImportErrorPrefix: "Local import failed",
      gitRequired: "Enter a repository URL",
      gitImportSuccess: "The repository snapshot was imported and entered unified version governance.",
      gitImportErrorTitle: "Repository snapshot import failed",
      gitImportErrorPrefix: "Repository import failed",
      catalogImportSuccess: (name: string) => `${name} was imported.`,
      catalogImportErrorTitle: (name: string) => `${name} import failed`,
      catalogImportErrorPrefix: "Market import failed",
      retryMissingPayload: "This history record does not contain retry parameters and may come from an older version.",
      retryImportSuccess: (title: string) => `${title} was imported again.`,
      retryImportErrorTitle: (title: string) => `${title} retry import failed`,
      retryImportErrorPrefix: "Retry import failed",
      importReadyTitle: (sourceLabel: string) => `${sourceLabel} import is preparing`,
      importReadyDetail: "Validating the input and creating the unified import context for this task.",
      importDispatchTitle: (sourceLabel: string) => `${sourceLabel} joined the unified pipeline`,
      importDispatchDetail: "The request was submitted. The backend will materialize the directory, archive it, and register its source.",
      importProcessingTitle: (sourceLabel: string) => `${sourceLabel} import is processing`,
      importProcessingDetail: "Waiting for the import to finish. The related workspace will open automatically after success.",
      importDoneTitle: (sourceLabel: string) => `${sourceLabel} import completed`,
      importDoneDetail: "The skill is now in the unified workspace, and you can keep reviewing source and version details.",
      importCompletedTitle: (name: string) => `${name} import completed`,
      unnamedRecord: "Untitled import record",
      historyDetailFallback: "There are no more import details for this record.",
      statusSuccess: "Success",
      statusFailed: "Failed",
      importSlugConflict: (slug: string) => `Slug ${slug} already exists. Rename the skill before importing.`,
      importSlugConflictWithSkill: (slug: string, name: string) =>
        `Slug ${slug} already belongs to ${name}. Open the existing skill or rename before importing.`,
    };
  }

  return {
    allCategory: "全部",
    allSources: "全部来源",
    importSteps: [
      { key: "prepare" as const, label: "接收请求", detail: "校验来源与导入参数" },
      { key: "dispatch" as const, label: "进入链路", detail: "提交统一导入事务" },
      { key: "processing" as const, label: "处理中", detail: "等待建档、快照与来源登记完成" },
      { key: "done" as const, label: "完成", detail: "准备进入个人技能库继续治理" },
    ],
    externalEyebrow: "外部技能资产市场",
    externalTitle: "发现成熟技能资产，并纳入个人技能库",
    externalSubtitle:
      "这里优先展示来自外部市场的成熟技能资产。你可以按榜单、关键词和类别筛选，再导入到统一导入链路。",
    externalSearchAria: "搜索外部技能资产",
    externalSearchPlaceholder: "搜索技能资产或仓库",
    externalAllTime: "总榜",
    externalTrending: "趋势",
    externalHot: "热门",
    externalResultsLabel: "外部市场",
    externalResultsTitle: "外部技能资产",
    externalResultsHint: "skills.sh",
    externalResultsCount: (count: number) => `共 ${count} 个技能资产`,
    externalSourcePrefix: (value: string) => `仓库 ${value}`,
    externalInstalls: (value: string) => `安装量 ${value}`,
    externalImportAction: "导入",
    externalImportSuccess: (name: string) => `已从外部市场导入 ${name}`,
    externalImportErrorTitle: (name: string) => `${name} 导入失败`,
    externalImportErrorPrefix: "外部市场导入失败",
    externalInstalled: "已在个人技能库",
    externalDetailAction: "查看详情",
    externalConflictAction: "查看已有资产",
    externalInstalledHint: (name: string) => `已在个人技能库中，当前名称为「${name}」。`,
    externalConflictHint: (name: string, slug: string) => `标识 ${slug} 已被现有技能资产「${name}」占用。`,
    externalDetailSummaryLabel: "能力概览",
    externalDetailRepoLabel: "来源仓库",
    externalDetailSkillIdLabel: "资产标识",
    externalDetailSourcePathLabel: "仓库路径",
    externalDetailDocumentPathLabel: "文档路径",
    externalDetailPreviewLabel: "文档摘要",
    externalDetailPreviewEmpty: "当前没有可预览的 README 或技能资产入口文档。",
    externalDetailLoadFailed: "外部技能资产详情加载失败",
    externalLoadFailed: "外部市场加载失败",
    externalNoResults: "当前筛选下没有匹配的外部技能资产",
    heroEyebrow: "",
    heroTitle: "市场与导入",
    heroSubtitle:
      "所有来源都会先进入同一条导入链路：目录物化、正式建档、初始快照、来源登记。市场与导入页同时承担外部发现、多来源导入、导入反馈和来源记录。",
    metricFeatured: "精选模板",
    metricCategories: "分类覆盖",
    metricTotal: "市场条目",
    metricSourceTypes: "已覆盖来源",
    quickImportLabel: "快速导入",
    quickImportTitle: "把技能资产纳入个人技能库",
    localSourceTitle: "本地目录",
    localSourceDescription: "导入已有的技能资产目录",
    pickFolder: "选择目录",
    repoImportLabel: "仓库快照导入",
    repoImportHint: "适合公共技能仓库或团队模板仓库",
    gitUrlAria: "Git 仓库地址",
    gitUrlPlaceholder: "输入 Git 仓库地址",
    gitSubdirAria: "仓库内技能子目录",
    gitSubdirPlaceholder: "可选：仓库内技能子目录",
    importFromRepo: "从仓库导入",
    importStatusLabel: "导入链路",
    importStatusWaiting: "等待新的导入任务",
    importStateRunning: "进行中",
    importStateFailed: "失败",
    importStateSuccess: "完成",
    importStateIdle: "空闲",
    importSourceLabel: "来源",
    importStageLabel: "阶段",
    importTargetLabel: "对象",
    importStatusHint: "发起导入后，这里展示当前导入链路状态。",
    importTarget: (name: string) => `当前导入对象：${name}`,
    pipelineLabel: "统一导入链路",
    pipelineTitle: "导入后自动完成的动作",
    pipelineStep1: "物化来源目录，统一校验为可导入技能资产",
    pipelineStep2: "建立正式技能资产记录并复制到个人技能库",
    pipelineStep3: "自动创建初始快照并设为当前生效版本",
    pipelineStep4: "写入 `skill_sources`，保留来源追溯信息",
    searchCatalogAria: "搜索市场模板",
    searchCatalogPlaceholder: "搜索市场模板、分类、标签或作者",
    governanceLabel: "来源治理",
    governanceTitle: "最近导入资产",
    governanceRecent: "最近 10 条",
    governanceHint: "按主来源筛选最近进入个人技能库的资产，并直接回看来源明细",
    sourceFilterLabel: "来源筛选",
    sourceFilterTitle: "按主来源回看最近导入资产",
    sourceFilterDescription: "这里优先展示最近更新的技能资产，并读取其正式主来源记录，便于检查导入后是否进入正确治理链路。",
    noGovernedAssets: "当前还没有导入资产",
    noGovernedAssetsForFilter: "当前来源筛选下没有匹配的技能资产",
    updatedAt: (value: string) => `更新于 ${value}`,
    sourceDetailFallback: "来源已登记，但当前没有更多可展示的明细。",
    primarySource: (label: string) => `主来源：${label}`,
    openWorkspace: "打开资产",
    historyLabel: "导入历史",
    historyTitle: "最近导入记录",
    historyCount: (count: number) => `共 ${count} 条`,
    historyHint: "保留成功与失败记录，便于回看问题、重复导入和继续进入个人技能库。",
    historySummaryLabel: "历史概览",
    historySummaryTitle: "统一导入留痕",
    historySummaryDescription: "每次导入都会登记来源、结果、目标技能资产与失败原因。失败记录可以直接重试，成功记录可以回到个人技能库继续治理。",
    success: "成功",
    failed: "失败",
    historyLoadFailed: "导入历史加载失败",
    reload: "重新加载",
    noHistory: "当前还没有导入历史记录",
    recordedAt: (value: string) => `记录于 ${value}`,
    sourceType: (label: string) => `来源类型：${label}`,
    retryImport: "重试导入",
    marketLoadFailed: "市场目录加载失败",
    featuredLabel: "精选模板",
    featuredTitle: "优先推荐",
    featuredHint: "优先覆盖平台同步、版本治理与团队空间三条主链路",
    importToWorkspace: "导入到个人技能库",
    catalogLabel: "市场目录",
    catalogTitle: "全部市场条目",
    catalogBadge: "统一市场目录",
    catalogCount: (count: number) => `当前结果 ${count} 项`,
    noCatalogItems: "没有找到匹配的市场条目",
    importAction: "导入",
    localImportSuccess: "本地目录已导入并建立初始快照",
    localImportErrorTitle: "本地目录导入失败",
    localImportErrorPrefix: "本地导入失败",
    gitRequired: "请输入仓库地址",
    gitImportSuccess: "仓库快照已导入并进入统一版本治理",
    gitImportErrorTitle: "仓库快照导入失败",
    gitImportErrorPrefix: "仓库导入失败",
    catalogImportSuccess: (name: string) => `已导入 ${name}`,
    catalogImportErrorTitle: (name: string) => `${name} 导入失败`,
    catalogImportErrorPrefix: "市场导入失败",
    retryMissingPayload: "该历史记录缺少重试参数，可能来自旧版本。",
    retryImportSuccess: (title: string) => `已重新导入 ${title}`,
    retryImportErrorTitle: (title: string) => `${title} 重试导入失败`,
    retryImportErrorPrefix: "重试导入失败",
    importReadyTitle: (sourceLabel: string) => `${sourceLabel} 导入准备中`,
    importReadyDetail: "正在校验输入，并为当前导入任务建立统一上下文。",
    importDispatchTitle: (sourceLabel: string) => `${sourceLabel} 已进入统一链路`,
    importDispatchDetail: "请求已经提交，后端将统一完成目录物化、正式建档与来源登记。",
    importProcessingTitle: (sourceLabel: string) => `${sourceLabel} 导入处理中`,
    importProcessingDetail: "正在等待导入完成，成功后会自动进入对应技能资产。",
    importDoneTitle: (sourceLabel: string) => `${sourceLabel} 导入完成`,
    importDoneDetail: "技能资产已经纳入个人技能库，可继续查看来源与版本。",
    importCompletedTitle: (name: string) => `${name} 已完成导入`,
    unnamedRecord: "未命名导入记录",
    historyDetailFallback: "当前记录没有更多导入明细。",
    statusSuccess: "成功",
    statusFailed: "失败",
    importSlugConflict: (slug: string) => `当前将生成标识 ${slug}，但该标识已存在，建议先改名后再导入。`,
    importSlugConflictWithSkill: (slug: string, name: string) =>
      `当前将生成标识 ${slug}，它已被技能资产「${name}」占用。建议先查看已有资产，或后续补充改名导入。`,
  };
}

export type MarketCopy = ReturnType<typeof getMarketCopy>;
